### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [tona30/Trabajo-final-2018-II#1]
Me parece bien el cambio. Entiendo ya tienes todo instalado y que pudiste bajar los datos sin problema.

Te faltan varios acentos en tu avance. Por favor corrígelos y cuida tu ortografía en general.

**Comment by tona30** [comment]
Ok gracias, no había tomado en cuenta el tema de la ortografía. En el último avance y el proyecto final tendré cuidado con la ortografía. Por el momento todo está instalado y funciona.

**Comment by tona30** [comment]
Ya corregí las faltas de ortografía del avance 2 voy a intentar hacerte un git pull del archivo modificado.

**Comment by tona30** [comment]
listo, según yo ya tienes el pull request del avance modificado, espero esté todo bien

**Comment by AliciaMstt** [comment]
Github sirve justamente para NO llenarse de archivos con nombres como avance2_final_elbueno_corregido.md sino que en un solo archivo avances2.md se pueda ir viendo el historial de cambios. 

Por lo tanto voy a ignorar tu pullrequest y te pido porfa que borres avance2Tonatiuhcorregido.md y hagas los cambios en avance2TonatiuhRR.md. Tómalo como un ejercicio para que te quede claro cómo funciona github. 

Avísame por aquí cuando esté hecho el cambio solicitado.

**Comment by tona30** [comment]
Ok gracias por los comentarios, justamente ese día tuve la duda si debía subir un archivo nuevo o corregir el previo. Ya me queda mas claro, entonces voy a eliminar el corregido y modificar el anterior.

**Comment by tona30** [comment]
Ya lo modifiqué desde mi rama y automáticamente se actualizó en mi liga de avance 2. Ya aparece actualizado desde el repo del curso, por lo que veo entonces ya no es necesario hacer pull request cada que se realizan cambios desde mi rama master, cierto?

**Comment by AliciaMstt** [comment]
El pull request es solo cuando quieres hacer un cambio en MI repo, es decir poner el link en Listado Proyectos finales. Lo que hagas en TU repo es muy tu onda y no me tienes que pedir pull request. :)
